kind: Pod
apiVersion: v1
metadata:
  name: duplicate-containers
spec:
  containers:
  - name: one
    image: openshift/hello-openshift:latest
  - name: two
    image: openshift/hello-openshift:latest
    env:
    - name: PORT
      value: "8081"
    - name: SECOND_PORT
      value: "8889"
