kind: BuildConfig
apiVersion: v1
metadata:
  name: hello-openshift
spec:
  source:
    type: Git
    git:
      uri: https://github.com/ellanos/hello-openshift-nodejs
      ref: master
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: hello-openshift:nodejs
