kind: ReplicationController
apiVersion: v1
metadata:
  name: hello-openshift
spec:
  replicas: 2
  template:
    metadata:
      labels:
        pod: hello-openshift
    spec:
      containers:
      - name: hello-openshift
        image: openshift/hello-openshift:latest
